_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 45
                - 55
            "2":
                - 1
                - 2
                - 3
                - 12
                - 45
                - 55
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.15
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
alg:
    value: PPO
alpha:
    value: 5
beta:
    value: 0.05
env_name:
    value: coins
human_env_config:
    value: coins_human
inequity_averse_reward:
    value: false
kl_threshold:
    value: 0.01
model:
    value: baseline
modified_env_config:
    value: coins_llm
num_agents:
    value: 5
num_cpus:
    value: 4
num_envs:
    value: 2
rollout_len:
    value: 10
seed:
    value: 42
total_timesteps:
    value: 10000
use_collective_reward:
    value: false
user_name:
    value: shuqing-shi
using_same_eval:
    value: true
